//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinba.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MenuResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sinba.Resources.Resources.MenuResource", typeof(MenuResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence.
        /// </summary>
        public static string Absence {
            get {
                return ResourceManager.GetString("Absence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence consécutive.
        /// </summary>
        public static string AbsenceConsecutive {
            get {
                return ResourceManager.GetString("AbsenceConsecutive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absentéisme.
        /// </summary>
        public static string Absenteisme {
            get {
                return ResourceManager.GetString("Absenteisme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accès.
        /// </summary>
        public static string Acces {
            get {
                return ResourceManager.GetString("Acces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution par age et matériel.
        /// </summary>
        public static string AgeAndMaterialDistributionReport {
            get {
                return ResourceManager.GetString("AgeAndMaterialDistributionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aide.
        /// </summary>
        public static string Aide {
            get {
                return ResourceManager.GetString("Aide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribution des parts de saignée.
        /// </summary>
        public static string AttributionPartSaignee {
            get {
                return ResourceManager.GetString("AttributionPartSaignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axe.
        /// </summary>
        public static string Axe {
            get {
                return ResourceManager.GetString("Axe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biological assets.
        /// </summary>
        public static string BiologicalAssetsReport {
            get {
                return ResourceManager.GetString("BiologicalAssetsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloc.
        /// </summary>
        public static string Bloc {
            get {
                return ResourceManager.GetString("Bloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        public static string Budget {
            get {
                return ResourceManager.GetString("Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de jours de saignée.
        /// </summary>
        public static string BudgetNombreJoursH {
            get {
                return ResourceManager.GetString("BudgetNombreJoursH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de jours de récolte.
        /// </summary>
        public static string BudgetNombreJoursP {
            get {
                return ResourceManager.GetString("BudgetNombreJoursP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objectif de production annuelle par bloc.
        /// </summary>
        public static string BudgetProductionAnnuelleBloc {
            get {
                return ResourceManager.GetString("BudgetProductionAnnuelleBloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Répartition mensuelle de la production.
        /// </summary>
        public static string BudgetRepartitiBudgetRepartitionProductionMensuelle {
            get {
                return ResourceManager.GetString("BudgetRepartitiBudgetRepartitionProductionMensuelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Répartition mensuelle de la production.
        /// </summary>
        public static string BudgetRepartitionProductionMensuelle {
            get {
                return ResourceManager.GetString("BudgetRepartitionProductionMensuelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre de coût.
        /// </summary>
        public static string CentreCout {
            get {
                return ResourceManager.GetString("CentreCout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champs.
        /// </summary>
        public static string Champs {
            get {
                return ResourceManager.GetString("Champs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cockpit.
        /// </summary>
        public static string Cockpit {
            get {
                return ResourceManager.GetString("Cockpit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code champ.
        /// </summary>
        public static string CodeChamp {
            get {
                return ResourceManager.GetString("CodeChamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comptabilisation des relevés WASP.
        /// </summary>
        public static string ComptabilisationSousTraitance {
            get {
                return ResourceManager.GetString("ComptabilisationSousTraitance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comptabilisation des relevés WASP.
        /// </summary>
        public static string ComptabilisationSousTraitanceReport {
            get {
                return ResourceManager.GetString("ComptabilisationSousTraitanceReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrôle.
        /// </summary>
        public static string Controle {
            get {
                return ResourceManager.GetString("Controle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts de saignée.
        /// </summary>
        public static string ControlePartSaignee {
            get {
                return ResourceManager.GetString("ControlePartSaignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prestation.
        /// </summary>
        public static string ControlePrestation {
            get {
                return ResourceManager.GetString("ControlePrestation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saignée.
        /// </summary>
        public static string ControleSaignee {
            get {
                return ResourceManager.GetString("ControleSaignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop Telex.
        /// </summary>
        public static string CropTelexReport {
            get {
                return ResourceManager.GetString("CropTelexReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily production report.
        /// </summary>
        public static string DailyProductionReport {
            get {
                return ResourceManager.GetString("DailyProductionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        public static string Division {
            get {
                return ResourceManager.GetString("Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budgétaires.
        /// </summary>
        public static string DonneesBudgetaires {
            get {
                return ResourceManager.GetString("DonneesBudgetaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Données externes.
        /// </summary>
        public static string DonneesExternes {
            get {
                return ResourceManager.GetString("DonneesExternes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industrielles.
        /// </summary>
        public static string DonneesIndustrielles {
            get {
                return ResourceManager.GetString("DonneesIndustrielles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry rubber content.
        /// </summary>
        public static string DryRubberContent {
            get {
                return ResourceManager.GetString("DryRubberContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer les absences.
        /// </summary>
        public static string EditerAbsence {
            get {
                return ResourceManager.GetString("EditerAbsence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoder prestation.
        /// </summary>
        public static string EncoderPrestation {
            get {
                return ResourceManager.GetString("EncoderPrestation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoder prime mensuelle.
        /// </summary>
        public static string EncoderPrimeMensuelle {
            get {
                return ResourceManager.GetString("EncoderPrimeMensuelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipe.
        /// </summary>
        public static string Equipe {
            get {
                return ResourceManager.GetString("Equipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipes sans OT.
        /// </summary>
        public static string EquipeSansOT {
            get {
                return ResourceManager.GetString("EquipeSansOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfert d&apos;équipe.
        /// </summary>
        public static string EquipeTransfert {
            get {
                return ResourceManager.GetString("EquipeTransfert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etat des surfaces.
        /// </summary>
        public static string EtatDesSurfacesReport {
            get {
                return ResourceManager.GetString("EtatDesSurfacesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evénement.
        /// </summary>
        public static string Evenement {
            get {
                return ResourceManager.GetString("Evenement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feuille de présence.
        /// </summary>
        public static string FeuillePresence {
            get {
                return ResourceManager.GetString("FeuillePresence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcellaire.
        /// </summary>
        public static string FieldSetupReport {
            get {
                return ResourceManager.GetString("FieldSetupReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonction.
        /// </summary>
        public static string Fonction {
            get {
                return ResourceManager.GetString("Fonction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fréquence saignée alternance.
        /// </summary>
        public static string FrequenceSaigneeAlternance {
            get {
                return ResourceManager.GetString("FrequenceSaigneeAlternance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion.
        /// </summary>
        public static string Gestion {
            get {
                return ResourceManager.GetString("Gestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groupe.
        /// </summary>
        public static string Groupe {
            get {
                return ResourceManager.GetString("Groupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide cheminement paramétrage.
        /// </summary>
        public static string GuideCheminementParametrage {
            get {
                return ResourceManager.GetString("GuideCheminementParametrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste.
        /// </summary>
        public static string Liste {
            get {
                return ResourceManager.GetString("Liste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livraisons journalières par engin.
        /// </summary>
        public static string LivraisonsJournalieresParEnginReport {
            get {
                return ResourceManager.GetString("LivraisonsJournalieresParEnginReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livraisons journalières.
        /// </summary>
        public static string LivraisonsJournalieresReport {
            get {
                return ResourceManager.GetString("LivraisonsJournalieresReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine.
        /// </summary>
        public static string Machine {
            get {
                return ResourceManager.GetString("Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des machines.
        /// </summary>
        public static string MachineListe {
            get {
                return ResourceManager.GetString("MachineListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Principal.
        /// </summary>
        public static string MainMenuText {
            get {
                return ResourceManager.GetString("MainMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maladie et traitement.
        /// </summary>
        public static string MaladieTraitement {
            get {
                return ResourceManager.GetString("MaladieTraitement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manuel utilisateur.
        /// </summary>
        public static string ManuelUtilisateur {
            get {
                return ResourceManager.GetString("ManuelUtilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Météo.
        /// </summary>
        public static string Meteo {
            get {
                return ResourceManager.GetString("Meteo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norme.
        /// </summary>
        public static string Norme {
            get {
                return ResourceManager.GetString("Norme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opération.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opération &amp; OT.
        /// </summary>
        public static string OperationOT {
            get {
                return ResourceManager.GetString("OperationOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        public static string Orientation {
            get {
                return ResourceManager.GetString("Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordre de travail.
        /// </summary>
        public static string OT {
            get {
                return ResourceManager.GetString("OT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturation OT.
        /// </summary>
        public static string OTFacturation {
            get {
                return ResourceManager.GetString("OTFacturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordres de travail sous-traitance.
        /// </summary>
        public static string OTSousTraitanceReport {
            get {
                return ResourceManager.GetString("OTSousTraitanceReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        public static string Parametres {
            get {
                return ResourceManager.GetString("Parametres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcelle.
        /// </summary>
        public static string Parcelle {
            get {
                return ResourceManager.GetString("Parcelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part de saignée.
        /// </summary>
        public static string PartSaignee {
            get {
                return ResourceManager.GetString("PartSaignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pays.
        /// </summary>
        public static string Pays {
            get {
                return ResourceManager.GetString("Pays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pente.
        /// </summary>
        public static string Pente {
            get {
                return ResourceManager.GetString("Pente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Période.
        /// </summary>
        public static string Periode {
            get {
                return ResourceManager.GetString("Periode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plante de couverture.
        /// </summary>
        public static string PlanteCouverture {
            get {
                return ResourceManager.GetString("PlanteCouverture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Précédent cultural.
        /// </summary>
        public static string PrecedentCultural {
            get {
                return ResourceManager.GetString("PrecedentCultural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prestation.
        /// </summary>
        public static string Prestation {
            get {
                return ResourceManager.GetString("Prestation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prestations doubles.
        /// </summary>
        public static string PrestationDouble {
            get {
                return ResourceManager.GetString("PrestationDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des prestations.
        /// </summary>
        public static string PrestationListe {
            get {
                return ResourceManager.GetString("PrestationListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prestation sans OT.
        /// </summary>
        public static string PrestationSansOT {
            get {
                return ResourceManager.GetString("PrestationSansOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime.
        /// </summary>
        public static string Prime {
            get {
                return ResourceManager.GetString("Prime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des primes.
        /// </summary>
        public static string PrimeListe {
            get {
                return ResourceManager.GetString("PrimeListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime mensuelle.
        /// </summary>
        public static string PrimeMensuelle {
            get {
                return ResourceManager.GetString("PrimeMensuelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string Production {
            get {
                return ResourceManager.GetString("Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profil {
            get {
                return ResourceManager.GetString("Profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapports.
        /// </summary>
        public static string Rapports {
            get {
                return ResourceManager.GetString("Rapports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recensement.
        /// </summary>
        public static string Recensement {
            get {
                return ResourceManager.GetString("Recensement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Récolte.
        /// </summary>
        public static string Recolte {
            get {
                return ResourceManager.GetString("Recolte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevés.
        /// </summary>
        public static string RelevePontBascule {
            get {
                return ResourceManager.GetString("RelevePontBascule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Répartition par age et par clone.
        /// </summary>
        public static string RepartitionParAgeEtParCloneReport {
            get {
                return ResourceManager.GetString("RepartitionParAgeEtParCloneReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressources Humaines.
        /// </summary>
        public static string RessourcesHumaines {
            get {
                return ResourceManager.GetString("RessourcesHumaines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saignée.
        /// </summary>
        public static string Saignee {
            get {
                return ResourceManager.GetString("Saignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche Menu.
        /// </summary>
        public static string SearchNullText {
            get {
                return ResourceManager.GetString("SearchNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string SectionEMS {
            get {
                return ResourceManager.GetString("SectionEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Société.
        /// </summary>
        public static string Societe {
            get {
                return ResourceManager.GetString("Societe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sous-traitance.
        /// </summary>
        public static string SousTraitance {
            get {
                return ResourceManager.GetString("SousTraitance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des sous-traitants.
        /// </summary>
        public static string SousTraitanceListe {
            get {
                return ResourceManager.GetString("SousTraitanceListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistiques.
        /// </summary>
        public static string Statistique {
            get {
                return ResourceManager.GetString("Statistique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistique opérationnelle.
        /// </summary>
        public static string StatistiqueOperationnelle {
            get {
                return ResourceManager.GetString("StatistiqueOperationnelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistiques paramétrage.
        /// </summary>
        public static string StatistiqueParametrage {
            get {
                return ResourceManager.GetString("StatistiqueParametrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistique production Hévéa.
        /// </summary>
        public static string StatistiqueProductionHeveaReport {
            get {
                return ResourceManager.GetString("StatistiqueProductionHeveaReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistique mensuelle production Hévéa.
        /// </summary>
        public static string StatistiqueProductionMensuelleHeveaReport {
            get {
                return ResourceManager.GetString("StatistiqueProductionMensuelleHeveaReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface &amp; Biological assets.
        /// </summary>
        public static string SurfaceAndBiologicalAssets {
            get {
                return ResourceManager.GetString("SurfaceAndBiologicalAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Par clone et année de planting.
        /// </summary>
        public static string SurfaceParCloneEtAnneeDePlantingReport {
            get {
                return ResourceManager.GetString("SurfaceParCloneEtAnneeDePlantingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Par type matériel &amp; année de planting.
        /// </summary>
        public static string SurfacePerMaterialReport {
            get {
                return ResourceManager.GetString("SurfacePerMaterialReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tâche exceptionnelle.
        /// </summary>
        public static string TacheExceptionnelle {
            get {
                return ResourceManager.GetString("TacheExceptionnelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taux d&apos;extraction.
        /// </summary>
        public static string TauxExtraction {
            get {
                return ResourceManager.GetString("TauxExtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technique d&apos;implantation.
        /// </summary>
        public static string TechniqueImplantation {
            get {
                return ResourceManager.GetString("TechniqueImplantation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technique de préparation du terrain.
        /// </summary>
        public static string TechniquePreparationTerrain {
            get {
                return ResourceManager.GetString("TechniquePreparationTerrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain.
        /// </summary>
        public static string Terrain {
            get {
                return ResourceManager.GetString("Terrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topographie.
        /// </summary>
        public static string Topographie {
            get {
                return ResourceManager.GetString("Topographie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travailleur.
        /// </summary>
        public static string Travailleur {
            get {
                return ResourceManager.GetString("Travailleur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travailleurs sans OT.
        /// </summary>
        public static string TravailleurSansOT {
            get {
                return ResourceManager.GetString("TravailleurSansOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Récapitulatif des travailleurs.
        /// </summary>
        public static string TravailleursRecap {
            get {
                return ResourceManager.GetString("TravailleursRecap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de machine.
        /// </summary>
        public static string TypeMachine {
            get {
                return ResourceManager.GetString("TypeMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de plantation.
        /// </summary>
        public static string TypePlantation {
            get {
                return ResourceManager.GetString("TypePlantation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unité.
        /// </summary>
        public static string Unite {
            get {
                return ResourceManager.GetString("Unite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateur.
        /// </summary>
        public static string Utilisateur {
            get {
                return ResourceManager.GetString("Utilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ville.
        /// </summary>
        public static string Ville {
            get {
                return ResourceManager.GetString("Ville", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WASP.
        /// </summary>
        public static string Wasp {
            get {
                return ResourceManager.GetString("Wasp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weighbridge daily production report.
        /// </summary>
        public static string WeighbridgeDailyProductionReport {
            get {
                return ResourceManager.GetString("WeighbridgeDailyProductionReport", resourceCulture);
            }
        }
    }
}
