//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinba.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportResource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sinba.Resources.Resources.ReportResource", typeof(ReportResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Année planting.
        /// </summary>
        public static string AnneePlanting {
            get {
                return ResourceManager.GetString("AnneePlanting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Août.
        /// </summary>
        public static string Aou {
            get {
                return ResourceManager.GetString("Aou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Article.
        /// </summary>
        public static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Avril.
        /// </summary>
        public static string Avr {
            get {
                return ResourceManager.GetString("Avr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Budget annuel.
        /// </summary>
        public static string BudgetAnnuel {
            get {
                return ResourceManager.GetString("BudgetAnnuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Centre de coût :.
        /// </summary>
        public static string CC {
            get {
                return ResourceManager.GetString("CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Centre de coût site :.
        /// </summary>
        public static string CCS {
            get {
                return ResourceManager.GetString("CCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Centre de coût.
        /// </summary>
        public static string CentreDeCout {
            get {
                return ResourceManager.GetString("CentreDeCout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CC Niv1.
        /// </summary>
        public static string CentreDeCoutN1 {
            get {
                return ResourceManager.GetString("CentreDeCoutN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CC Niv2.
        /// </summary>
        public static string CentreDeCoutN2 {
            get {
                return ResourceManager.GetString("CentreDeCoutN2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CC Niv3.
        /// </summary>
        public static string CentreDeCoutN3 {
            get {
                return ResourceManager.GetString("CentreDeCoutN3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Centre de coût site.
        /// </summary>
        public static string CentreDeCoutSite {
            get {
                return ResourceManager.GetString("CentreDeCoutSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Article.
        /// </summary>
        public static string CritereArticle {
            get {
                return ResourceManager.GetString("CritereArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination.
        /// </summary>
        public static string CritereDestination {
            get {
                return ResourceManager.GetString("CritereDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nature.
        /// </summary>
        public static string CritereNature {
            get {
                return ResourceManager.GetString("CritereNature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cumul en montant.
        /// </summary>
        public static string CumulFranc {
            get {
                return ResourceManager.GetString("CumulFranc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cumul en Uo.
        /// </summary>
        public static string CumulUo {
            get {
                return ResourceManager.GetString("CumulUo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Décembre.
        /// </summary>
        public static string Dec {
            get {
                return ResourceManager.GetString("Dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Désignation.
        /// </summary>
        public static string Designation {
            get {
                return ResourceManager.GetString("Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination :.
        /// </summary>
        public static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exercice.
        /// </summary>
        public static string Exercice {
            get {
                return ResourceManager.GetString("Exercice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fevrier.
        /// </summary>
        public static string Fev {
            get {
                return ResourceManager.GetString("Fev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Janvier.
        /// </summary>
        public static string Janv {
            get {
                return ResourceManager.GetString("Janv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Juillet.
        /// </summary>
        public static string Juil {
            get {
                return ResourceManager.GetString("Juil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Juin.
        /// </summary>
        public static string Juin {
            get {
                return ResourceManager.GetString("Juin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mai.
        /// </summary>
        public static string Mai {
            get {
                return ResourceManager.GetString("Mai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mars.
        /// </summary>
        public static string Mar {
            get {
                return ResourceManager.GetString("Mar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant.
        /// </summary>
        public static string Montant {
            get {
                return ResourceManager.GetString("Montant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nat Uo.
        /// </summary>
        public static string NatUo {
            get {
                return ResourceManager.GetString("NatUo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nature :.
        /// </summary>
        public static string Nature {
            get {
                return ResourceManager.GetString("Nature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nat. Niv1.
        /// </summary>
        public static string NatureN1 {
            get {
                return ResourceManager.GetString("NatureN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nat. Niv2.
        /// </summary>
        public static string NatureN2 {
            get {
                return ResourceManager.GetString("NatureN2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nat. Niv3.
        /// </summary>
        public static string NatureN3 {
            get {
                return ResourceManager.GetString("NatureN3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nb Uo.
        /// </summary>
        public static string NbUo {
            get {
                return ResourceManager.GetString("NbUo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Novembre.
        /// </summary>
        public static string Nov {
            get {
                return ResourceManager.GetString("Nov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Octobre.
        /// </summary>
        public static string Oct {
            get {
                return ResourceManager.GetString("Oct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prévision budget en montant.
        /// </summary>
        public static string PrevisionBudgetFranc {
            get {
                return ResourceManager.GetString("PrevisionBudgetFranc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prévision budget en Uo.
        /// </summary>
        public static string PrevisionBudgetUo {
            get {
                return ResourceManager.GetString("PrevisionBudgetUo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prix Unitaire.
        /// </summary>
        public static string PrixUnit {
            get {
                return ResourceManager.GetString("PrixUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rapport0.
        /// </summary>
        public static string Rapport0 {
            get {
                return ResourceManager.GetString("Rapport0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rapport1.
        /// </summary>
        public static string Rapport1 {
            get {
                return ResourceManager.GetString("Rapport1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rapport2.
        /// </summary>
        public static string Rapport2 {
            get {
                return ResourceManager.GetString("Rapport2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rapport3.
        /// </summary>
        public static string Rapport3 {
            get {
                return ResourceManager.GetString("Rapport3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Septembre.
        /// </summary>
        public static string Sept {
            get {
                return ResourceManager.GetString("Sept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Site.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total nature :.
        /// </summary>
        public static string TotalNature {
            get {
                return ResourceManager.GetString("TotalNature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version.
        /// </summary>
        public static string VersionBudget {
            get {
                return ResourceManager.GetString("VersionBudget", resourceCulture);
            }
        }
    }
}
