//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinba.Gui.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sinba.Gui.Resources.AccountResource", typeof(AccountResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        public static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deconnexion.
        /// </summary>
        public static string btnLogout {
            get {
                return ResourceManager.GetString("btnLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription.
        /// </summary>
        public static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réinitialiser.
        /// </summary>
        public static string btnReset {
            get {
                return ResourceManager.GetString("btnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoyer.
        /// </summary>
        public static string btnSend {
            get {
                return ResourceManager.GetString("btnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci d&apos;avoir confirmer votre adresse e-mail. .
        /// </summary>
        public static string ConfirmEmailMsg {
            get {
                return ResourceManager.GetString("ConfirmEmailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation e-mail.
        /// </summary>
        public static string ConfirmEmailTitle {
            get {
                return ResourceManager.GetString("ConfirmEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tentative de connexion non valide..
        /// </summary>
        public static string errorLoginInvalidLoginAttempt {
            get {
                return ResourceManager.GetString("errorLoginInvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez avoir une adresse mail confirmée pour vous connecter. Une confirmation a été envoyé à votre compte e-mail..
        /// </summary>
        public static string errorLoginMustConfirmEmail {
            get {
                return ResourceManager.GetString("errorLoginMustConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vérifiez votre e-mail et validez votre compte. Votre compte doit être confirmé avant de pouvoir vous connecter..
        /// </summary>
        public static string errorRegisterMustConfirmEmail {
            get {
                return ResourceManager.GetString("errorRegisterMustConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code invalide..
        /// </summary>
        public static string errorVerifyCodeInvalidCode {
            get {
                return ResourceManager.GetString("errorVerifyCodeInvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci de vérifier votre e-mail pour réinitialiser votre mot de passe..
        /// </summary>
        public static string ForgotPasswordConfirmationMsg {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Renvoi de mot de passe.
        /// </summary>
        public static string ForgotPasswordConfirmationTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci de réinitialiser votre mot de passe en cliquant &lt;a href={0}&gt;sur ce lien&lt;/a&gt;.
        /// </summary>
        public static string ForgotPasswordEmailBody {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau mot de passe.
        /// </summary>
        public static string ForgotPasswordEmailSubject {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demande de renvoi de mot de passe.
        /// </summary>
        public static string ForgotPasswordTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chargement des sites....
        /// </summary>
        public static string LoadingSites {
            get {
                return ResourceManager.GetString("LoadingSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cliquez ici pour vous connecter..
        /// </summary>
        public static string LoginConfirmEmailText {
            get {
                return ResourceManager.GetString("LoginConfirmEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmez votre compte - Renvoi.
        /// </summary>
        public static string LoginEmailConfirmationSubject {
            get {
                return ResourceManager.GetString("LoginEmailConfirmationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe oublié ?.
        /// </summary>
        public static string LoginForgotPasswordQuestion {
            get {
                return ResourceManager.GetString("LoginForgotPasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compte verrouillé.
        /// </summary>
        public static string LoginLockoutTitle {
            get {
                return ResourceManager.GetString("LoginLockoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenue .
        /// </summary>
        public static string LoginWelcomeText {
            get {
                return ResourceManager.GetString("LoginWelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gérer votre compte.
        /// </summary>
        public static string LoginWelcomeTextTitle {
            get {
                return ResourceManager.GetString("LoginWelcomeTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous ne disposez pas des autorisations requises pour accéder à cette fonction..
        /// </summary>
        public static string NotAuthorizedMessage {
            get {
                return ResourceManager.GetString("NotAuthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accès refusé.
        /// </summary>
        public static string NotAuthorizedTitle {
            get {
                return ResourceManager.GetString("NotAuthorizedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmez votre compte.
        /// </summary>
        public static string RegisterEmailConfirmationSubject {
            get {
                return ResourceManager.GetString("RegisterEmailConfirmationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cliquez sur ce lien pour vous connectez..
        /// </summary>
        public static string ResetPasswordConfirmationLinkText {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmationLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre mot de passe a été réinitialisé..
        /// </summary>
        public static string ResetPasswordConfirmationMsg {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation de réinitialisation de mot de passe.
        /// </summary>
        public static string ResetPasswordConfirmationTitle {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réinitialisation mot de passe.
        /// </summary>
        public static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci de confirmer votre compte en cliquant &lt;a href={0}&gt;sur ce lien&lt;/a&gt;.
        /// </summary>
        public static string SendEmailConfirmationTokenEmailBody {
            get {
                return ResourceManager.GetString("SendEmailConfirmationTokenEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonjour,&lt;br/&gt;&lt;br/&gt;Un compte Sinba a été créé pour vous. &lt;a href={0}&gt;Cliquez sur ce lien pour saisir un nouveau mot de passe&lt;/a&gt;. .
        /// </summary>
        public static string SendUserPasswordCreationTokenEmailBody {
            get {
                return ResourceManager.GetString("SendUserPasswordCreationTokenEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sinba - Création de votre mot de passe.
        /// </summary>
        public static string SendUserPasswordCreationTokenEmailSubject {
            get {
                return ResourceManager.GetString("SendUserPasswordCreationTokenEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utilisateur:  {0} - Types utilisateur.
        /// </summary>
        public static string TypeUtilisateurPageTitle {
            get {
                return ResourceManager.GetString("TypeUtilisateurPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;utilisateur possède déjà ce type.
        /// </summary>
        public static string UserAlreadyGetRight {
            get {
                return ResourceManager.GetString("UserAlreadyGetRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les dates chevauchent .
        /// </summary>
        public static string UserChevaucheDateForType {
            get {
                return ResourceManager.GetString("UserChevaucheDateForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vérification.
        /// </summary>
        public static string VerifyCodeTitle {
            get {
                return ResourceManager.GetString("VerifyCodeTitle", resourceCulture);
            }
        }
    }
}
