//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinba.Gui.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sinba.Gui.Resources.CommonResource", typeof(CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun.
        /// </summary>
        public static string Aucun {
            get {
                return ResourceManager.GetString("Aucun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter.
        /// </summary>
        public static string btnAddTooltip {
            get {
                return ResourceManager.GetString("btnAddTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher.
        /// </summary>
        public static string btnAfficher {
            get {
                return ResourceManager.GetString("btnAfficher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non.
        /// </summary>
        public static string btnCancel1 {
            get {
                return ResourceManager.GetString("btnCancel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fermer.
        /// </summary>
        public static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmer.
        /// </summary>
        public static string btnConfirmer {
            get {
                return ResourceManager.GetString("btnConfirmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Consulter.
        /// </summary>
        public static string btnConsulter {
            get {
                return ResourceManager.GetString("btnConsulter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;historique ne peut pas être supprimé..
        /// </summary>
        public static string btnDeleteHistoryNotAuthorised {
            get {
                return ResourceManager.GetString("btnDeleteHistoryNotAuthorised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression non autorisée. Des données sont attachées..
        /// </summary>
        public static string btnDeleteIsUsed {
            get {
                return ResourceManager.GetString("btnDeleteIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string btnDeleteTooltip {
            get {
                return ResourceManager.GetString("btnDeleteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dupliquer.
        /// </summary>
        public static string btnDupliquer {
            get {
                return ResourceManager.GetString("btnDupliquer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;historique ne peut pas être modifié..
        /// </summary>
        public static string btnEditHistoryNotAuthorised {
            get {
                return ResourceManager.GetString("btnEditHistoryNotAuthorised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification non autorisée. Des données sont attachées..
        /// </summary>
        public static string btnEditIsUsed {
            get {
                return ResourceManager.GetString("btnEditIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        public static string btnEditTooltip {
            get {
                return ResourceManager.GetString("btnEditTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Générer.
        /// </summary>
        public static string btnGenerer {
            get {
                return ResourceManager.GetString("btnGenerer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Importer.
        /// </summary>
        public static string btnImporter {
            get {
                return ResourceManager.GetString("btnImporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Descendre.
        /// </summary>
        public static string btnMoveDown {
            get {
                return ResourceManager.GetString("btnMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Monter.
        /// </summary>
        public static string btnMoveUp {
            get {
                return ResourceManager.GetString("btnMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rejeter.
        /// </summary>
        public static string btnRejeter {
            get {
                return ResourceManager.GetString("btnRejeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Répartir.
        /// </summary>
        public static string btnRepartir {
            get {
                return ResourceManager.GetString("btnRepartir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string btnSupprimer {
            get {
                return ResourceManager.GetString("btnSupprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous n&apos;êtes pas autorisé à effectuer cette action..
        /// </summary>
        public static string btnTooltipNotAuthorised {
            get {
                return ResourceManager.GetString("btnTooltipNotAuthorised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mettre à jour.
        /// </summary>
        public static string btnUpdate {
            get {
                return ResourceManager.GetString("btnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider.
        /// </summary>
        public static string btnValider {
            get {
                return ResourceManager.GetString("btnValider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oui.
        /// </summary>
        public static string btnValider1 {
            get {
                return ResourceManager.GetString("btnValider1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commentaire.
        /// </summary>
        public static string Commentaire {
            get {
                return ResourceManager.GetString("Commentaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous supprimer cet enregistrement ?.
        /// </summary>
        public static string confirmDelete {
            get {
                return ResourceManager.GetString("confirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez un écart de .
        /// </summary>
        public static string confirmEcart {
            get {
                return ResourceManager.GetString("confirmEcart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous continuer ?.
        /// </summary>
        public static string confirmValidation {
            get {
                return ResourceManager.GetString("confirmValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mettre à jour.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un ou plusieurs champs obligatoires n&apos;ont pas été renseignés..
        /// </summary>
        public static string errorChampRequis {
            get {
                return ResourceManager.GetString("errorChampRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous ne disposez pas des autorisations requises pour ces données..
        /// </summary>
        public static string errorDataInaccessible {
            get {
                return ResourceManager.GetString("errorDataInaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet enregistrement est utilisé et ne peut pas être supprimée..
        /// </summary>
        public static string errorDeleteRecordUsed {
            get {
                return ResourceManager.GetString("errorDeleteRecordUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreure est survenue..
        /// </summary>
        public static string errorGeneralError {
            get {
                return ResourceManager.GetString("errorGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous ne disposez pas des autorisations requises pour ce site..
        /// </summary>
        public static string errorSiteInaccessible {
            get {
                return ResourceManager.GetString("errorSiteInaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir au minimum {0} caratères.
        /// </summary>
        public static string filterMinLength {
            get {
                return ResourceManager.GetString("filterMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ici.
        /// </summary>
        public static string Ici {
            get {
                return ResourceManager.GetString("Ici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (Kg).
        /// </summary>
        public static string Kilogramme {
            get {
                return ResourceManager.GetString("Kilogramme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Critères de sélection.
        /// </summary>
        public static string lblCritere {
            get {
                return ResourceManager.GetString("lblCritere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exporter en {0}.
        /// </summary>
        public static string lblExportTo {
            get {
                return ResourceManager.GetString("lblExportTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chargement en cours....
        /// </summary>
        public static string lblLoading {
            get {
                return ResourceManager.GetString("lblLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prévisions.
        /// </summary>
        public static string lblPrevision {
            get {
                return ResourceManager.GetString("lblPrevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recherche de {0}.
        /// </summary>
        public static string lblRecherche {
            get {
                return ResourceManager.GetString("lblRecherche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Data.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous n&apos;êtes pas autorisé à effectuer cette action..
        /// </summary>
        public static string NotAuthorised {
            get {
                return ResourceManager.GetString("NotAuthorised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rejeté.
        /// </summary>
        public static string Rejete {
            get {
                return ResourceManager.GetString("Rejete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repartition.
        /// </summary>
        public static string Repartition {
            get {
                return ResourceManager.GetString("Repartition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retirer.
        /// </summary>
        public static string Retirer {
            get {
                return ResourceManager.GetString("Retirer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validation.
        /// </summary>
        public static string Validation {
            get {
                return ResourceManager.GetString("Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validé.
        /// </summary>
        public static string Valide {
            get {
                return ResourceManager.GetString("Valide", resourceCulture);
            }
        }
    }
}
