//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinba.Resources.Resources.Entity {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EntityCommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntityCommonResource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sinba.Resources.Resources.Entity.EntityCommonResource", typeof(EntityCommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accueil.
        /// </summary>
        public static string Accueil {
            get {
                return ResourceManager.GetString("Accueil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aide en ligne.
        /// </summary>
        public static string Aide {
            get {
                return ResourceManager.GetString("Aide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajout planteur.
        /// </summary>
        public static string AjoutPlanteur {
            get {
                return ResourceManager.GetString("AjoutPlanteur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajout projet planteur.
        /// </summary>
        public static string AjoutProjetPlanteur {
            get {
                return ResourceManager.GetString("AjoutProjetPlanteur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        public static string Annuler {
            get {
                return ResourceManager.GetString("Annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Articles.
        /// </summary>
        public static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les données non enregistrées seront perdues. Voulez-vous continuez ?.
        /// </summary>
        public static string BatchEditChangesLossMsg {
            get {
                return ResourceManager.GetString("BatchEditChangesLossMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abattage total.
        /// </summary>
        public static string BlocNombreEmplacementFinalRemarque {
            get {
                return ResourceManager.GetString("BlocNombreEmplacementFinalRemarque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annulation.
        /// </summary>
        public static string Canceling {
            get {
                return ResourceManager.GetString("Canceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Case à cocher.
        /// </summary>
        public static string CaseACocher {
            get {
                return ResourceManager.GetString("CaseACocher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clôturé.
        /// </summary>
        public static string Cloture {
            get {
                return ResourceManager.GetString("Cloture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code(s) inexistant(s).
        /// </summary>
        public static string CodeNotExists {
            get {
                return ResourceManager.GetString("CodeNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion en cours.
        /// </summary>
        public static string ConnexionEnCours {
            get {
                return ResourceManager.GetString("ConnexionEnCours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Critères.
        /// </summary>
        public static string Critere {
            get {
                return ResourceManager.GetString("Critere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Critères de duplication.
        /// </summary>
        public static string CriteresDuplication {
            get {
                return ResourceManager.GetString("CriteresDuplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vérification des données.
        /// </summary>
        public static string DataChecking {
            get {
                return ResourceManager.GetString("DataChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrement des données.
        /// </summary>
        public static string DataSaving {
            get {
                return ResourceManager.GetString("DataSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Densité arbres saignables.
        /// </summary>
        public static string DensiteArbresSaignables {
            get {
                return ResourceManager.GetString("DensiteArbresSaignables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Doublons.
        /// </summary>
        public static string Doublons {
            get {
                return ResourceManager.GetString("Doublons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dupliquer sur.
        /// </summary>
        public static string DupliquerSur {
            get {
                return ResourceManager.GetString("DupliquerSur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur(s).
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce champ ne peut contenir que des chiffres, des lettres et des tirets.
        /// </summary>
        public static string errorAlphanumericField {
            get {
                return ResourceManager.GetString("errorAlphanumericField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette date de début existe déjà pour le bloc {0}.
        /// </summary>
        public static string errorBeginingDateExists {
            get {
                return ResourceManager.GetString("errorBeginingDateExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce code existe déjà pour la société sélectionnée!.
        /// </summary>
        public static string errorCodeAndSocieteExists {
            get {
                return ResourceManager.GetString("errorCodeAndSocieteExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce code existe déjà.
        /// </summary>
        public static string errorCodeExists {
            get {
                return ResourceManager.GetString("errorCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce contact existe déjà!.
        /// </summary>
        public static string errorContactExiste {
            get {
                return ResourceManager.GetString("errorContactExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur totale des {0} doit être égale à {1}..
        /// </summary>
        public static string errorCumul {
            get {
                return ResourceManager.GetString("errorCumul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet intervale est partielerment ou entièrement déjà défini.
        /// </summary>
        public static string errorDateOverloaps {
            get {
                return ResourceManager.GetString("errorDateOverloaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La modification des lignes importées d&apos;EMSAGRO n&apos;est pas autorisée.
        /// </summary>
        public static string errorDeleteImportRow {
            get {
                return ResourceManager.GetString("errorDeleteImportRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ {0} doit contenir entre {2} et {1} caractères.
        /// </summary>
        public static string errorFieldLength {
            get {
                return ResourceManager.GetString("errorFieldLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ {0} ne doit pas dépasser {1} caractères.
        /// </summary>
        public static string errorFieldMaxLength {
            get {
                return ResourceManager.GetString("errorFieldMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format des données invalides.
        /// </summary>
        public static string errorFormatDesDonneesInvalides {
            get {
                return ResourceManager.GetString("errorFormatDesDonneesInvalides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ {0} doit être plus grand que la valeur minimum.
        /// </summary>
        public static string errorGreatherThan {
            get {
                return ResourceManager.GetString("errorGreatherThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet identifiant est déjà utilisé.
        /// </summary>
        public static string errorIdExists {
            get {
                return ResourceManager.GetString("errorIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette immatriculation est déjà utilisée.
        /// </summary>
        public static string errorImmatriculationExists {
            get {
                return ResourceManager.GetString("errorImmatriculationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse mail invalide.
        /// </summary>
        public static string errorInvalidEmail {
            get {
                return ResourceManager.GetString("errorInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce libellé est déjà utilisé.
        /// </summary>
        public static string errorLibelleExists {
            get {
                return ResourceManager.GetString("errorLibelleExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login ou mot de passe incorrect .
        /// </summary>
        public static string errorLoginPassword {
            get {
                return ResourceManager.GetString("errorLoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce nom existe déjà.
        /// </summary>
        public static string errorNomExists {
            get {
                return ResourceManager.GetString("errorNomExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce panneau a déjà  été utilisé sur ce bloc dans cette version de budget, veuillez changer de panneau.
        /// </summary>
        public static string errorPanneauExists {
            get {
                return ResourceManager.GetString("errorPanneauExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le mot de passe et la confirmation ne correspondent pas.
        /// </summary>
        public static string errorPasswordConfirmation {
            get {
                return ResourceManager.GetString("errorPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Propriété {0} introuvable.
        /// </summary>
        public static string errorProprieteIntrouvable {
            get {
                return ResourceManager.GetString("errorProprieteIntrouvable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur de {0} doit être entre {1} et {2}..
        /// </summary>
        public static string errorRange {
            get {
                return ResourceManager.GetString("errorRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un recensement existe déjà pour ce bloc à cette date..
        /// </summary>
        public static string errorRecensementExists {
            get {
                return ResourceManager.GetString("errorRecensementExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ {0} est obligatoire.
        /// </summary>
        public static string errorRequiredField {
            get {
                return ResourceManager.GetString("errorRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce mot ne peut pas être utilisé..
        /// </summary>
        public static string errorReservedWord {
            get {
                return ResourceManager.GetString("errorReservedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de l&apos;enregistrement des données!.
        /// </summary>
        public static string errorSavindData {
            get {
                return ResourceManager.GetString("errorSavindData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un site avec le même identifiant est déjà défini pour cette société.
        /// </summary>
        public static string errorSiteIdExists {
            get {
                return ResourceManager.GetString("errorSiteIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce champ est obligatoire.
        /// </summary>
        public static string errorThisFieldIsRequired {
            get {
                return ResourceManager.GetString("errorThisFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette valeur doit être unique..
        /// </summary>
        public static string errorUniqueValue {
            get {
                return ResourceManager.GetString("errorUniqueValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur doit être supérieure à {0}..
        /// </summary>
        public static string errorUpTo {
            get {
                return ResourceManager.GetString("errorUpTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format du champ est incorrecte.
        /// </summary>
        public static string errorWrongFormat {
            get {
                return ResourceManager.GetString("errorWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exporter vers.
        /// </summary>
        public static string ExportTo {
            get {
                return ResourceManager.GetString("ExportTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Facturée le &lt;b&gt;{0}&lt;/b&gt; par &lt;b&gt;{1}&lt;/b&gt; .
        /// </summary>
        public static string FactureLePar {
            get {
                return ResourceManager.GetString("FactureLePar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hévéa.
        /// </summary>
        public static string Hevea {
            get {
                return ResourceManager.GetString("Hevea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identification.
        /// </summary>
        public static string Identification {
            get {
                return ResourceManager.GetString("Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impoossible de supprimer.
        /// </summary>
        public static string ImpoossibleSupprime {
            get {
                return ResourceManager.GetString("ImpoossibleSupprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de supprimer.
        /// </summary>
        public static string ImpossibleSupprime {
            get {
                return ResourceManager.GetString("ImpossibleSupprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coefficients.
        /// </summary>
        public static string labelCoefficient {
            get {
                return ResourceManager.GetString("labelCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Critères.
        /// </summary>
        public static string labelCritere {
            get {
                return ResourceManager.GetString("labelCritere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valeurs unité d&apos;oeuvre.
        /// </summary>
        public static string labelValeurUO {
            get {
                return ResourceManager.GetString("labelValeurUO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifié(e).
        /// </summary>
        public static string lblModifie {
            get {
                return ResourceManager.GetString("lblModifie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non Modifié(e).
        /// </summary>
        public static string lblNonModifie {
            get {
                return ResourceManager.GetString("lblNonModifie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Libellé Article.
        /// </summary>
        public static string LibelleArticle {
            get {
                return ResourceManager.GetString("LibelleArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ligne(s).
        /// </summary>
        public static string Ligne {
            get {
                return ResourceManager.GetString("Ligne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste à choix multiples.
        /// </summary>
        public static string ListeAChoixMultiples {
            get {
                return ResourceManager.GetString("ListeAChoixMultiples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste déroulante.
        /// </summary>
        public static string ListeDeroulante {
            get {
                return ResourceManager.GetString("ListeDeroulante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chargement.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification planteur.
        /// </summary>
        public static string ModifPlanteur {
            get {
                return ResourceManager.GetString("ModifPlanteur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification projet planteur.
        /// </summary>
        public static string ModifProjetPlanteur {
            get {
                return ResourceManager.GetString("ModifProjetPlanteur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun centre de coût site correspondant n&apos;a été trouvé.
        /// </summary>
        public static string msgCCSIntrouvable {
            get {
                return ResourceManager.GetString("msgCCSIntrouvable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous augmenter le crédit de cet ordre de travail ?.
        /// </summary>
        public static string msgConfirmAugmenterCredit {
            get {
                return ResourceManager.GetString("msgConfirmAugmenterCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous annuler la saisie en cours ?.
        /// </summary>
        public static string msgConfirmCancel {
            get {
                return ResourceManager.GetString("msgConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous clôturer cet ordre de travail ?.
        /// </summary>
        public static string msgConfirmCloturer {
            get {
                return ResourceManager.GetString("msgConfirmCloturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous supprimer cet enregistrement ?.
        /// </summary>
        public static string msgConfirmDelete {
            get {
                return ResourceManager.GetString("msgConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous prolonger cet ordre de travail ?.
        /// </summary>
        public static string msgConfirmProlonger {
            get {
                return ResourceManager.GetString("msgConfirmProlonger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous réceptionner cet ordre de travail ?.
        /// </summary>
        public static string msgConfirmReceptionner {
            get {
                return ResourceManager.GetString("msgConfirmReceptionner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous relancer la validation de cet ordre de travail ?.
        /// </summary>
        public static string msgConfirmRelanceOT {
            get {
                return ResourceManager.GetString("msgConfirmRelanceOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Echec de l&apos;opération.
        /// </summary>
        public static string msgFailure {
            get {
                return ResourceManager.GetString("msgFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Opération effectuée avec succès!.
        /// </summary>
        public static string msgSuccess {
            get {
                return ResourceManager.GetString("msgSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La surface totale doit correspondre à la surface de {0}  ha géolocalisée..
        /// </summary>
        public static string msgValidationSurfaceGeo {
            get {
                return ResourceManager.GetString("msgValidationSurfaceGeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nombre d’emplacement doit être égal : arbres exploitables + arbres immatures + arbres en arrêt de saignée + emplacements vides..
        /// </summary>
        public static string msgValidRecensement1 {
            get {
                return ResourceManager.GetString("msgValidRecensement1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nombre d’arbres vivants doit être égal : arbres immatures + arbres exploitables + arbres en arrêt de saignée..
        /// </summary>
        public static string msgValidRecensement2 {
            get {
                return ResourceManager.GetString("msgValidRecensement2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nombre d’emplacement doit être égal : arbres sains + arbres malades+ emplacements vides..
        /// </summary>
        public static string msgValidRecensement3 {
            get {
                return ResourceManager.GetString("msgValidRecensement3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre d’années de culture.
        /// </summary>
        public static string NombreAnneesCulture {
            get {
                return ResourceManager.GetString("NombreAnneesCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre d’années d’exploitation.
        /// </summary>
        public static string NombreAnneesExploitation {
            get {
                return ResourceManager.GetString("NombreAnneesExploitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non.
        /// </summary>
        public static string Non {
            get {
                return ResourceManager.GetString("Non", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numérique.
        /// </summary>
        public static string Numerique {
            get {
                return ResourceManager.GetString("Numerique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oui.
        /// </summary>
        public static string Oui {
            get {
                return ResourceManager.GetString("Oui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Palmier.
        /// </summary>
        public static string Palmier {
            get {
                return ResourceManager.GetString("Palmier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres.
        /// </summary>
        public static string Parametres {
            get {
                return ResourceManager.GetString("Parametres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Personne morale.
        /// </summary>
        public static string PersonneMorale {
            get {
                return ResourceManager.GetString("PersonneMorale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Personne physique.
        /// </summary>
        public static string PersonnePhysique {
            get {
                return ResourceManager.GetString("PersonnePhysique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prix unitaire dupliqué / existant.
        /// </summary>
        public static string Prixunitaireduplique {
            get {
                return ResourceManager.GetString("Prixunitaireduplique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prix unitaire à dupliquer.
        /// </summary>
        public static string PrixunitaireDupliquer {
            get {
                return ResourceManager.GetString("PrixunitaireDupliquer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rejeté.
        /// </summary>
        public static string Rejete {
            get {
                return ResourceManager.GetString("Rejete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression projet planteur.
        /// </summary>
        public static string SuppProjetPlanteur {
            get {
                return ResourceManager.GetString("SuppProjetPlanteur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression plantation.
        /// </summary>
        public static string SuppressionPlantation {
            get {
                return ResourceManager.GetString("SuppressionPlantation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Surface.
        /// </summary>
        public static string Surface {
            get {
                return ResourceManager.GetString("Surface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tous.
        /// </summary>
        public static string Tous {
            get {
                return ResourceManager.GetString("Tous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toutes.
        /// </summary>
        public static string Toutes {
            get {
                return ResourceManager.GetString("Toutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travailleurs encodés sans contrat.
        /// </summary>
        public static string TravailleursEncodesSansContrat {
            get {
                return ResourceManager.GetString("TravailleursEncodesSansContrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travailleurs sans prestation.
        /// </summary>
        public static string TravailleursSansPrestation {
            get {
                return ResourceManager.GetString("TravailleursSansPrestation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XLS.
        /// </summary>
        public static string Xls {
            get {
                return ResourceManager.GetString("Xls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XLSX.
        /// </summary>
        public static string Xlsx {
            get {
                return ResourceManager.GetString("Xlsx", resourceCulture);
            }
        }
    }
}
